hotreload_theme = true
force_keyboard_focus = true
hide_quick_activation = true

[builtins.commands]
hidden = true

[builtins.symbols]
after_copy = ""
hidden = true

[builtins.finder]
use_fd = true
cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
icon = "file"
name = "Finder"
preview_images = true
hidden = false
prefix = "."

[providers]

empty = []
